type ServiceItem = { title: string; text: string };
type SpaceItem = { title: string; text: string };
type ValueItem = { title: string; text: string };

export type Messages = {
  meta: {
    description: string;
    roomsTitle: string;
    roomsDescription: string;
    galleryTitle: string;
    galleryDescription: string;
    aboutTitle: string;
    aboutDescription: string;
    contactTitle: string;
    contactDescription: string;
    roomNotFound: string;
  };
  nav: {
    home: string;
    rooms: string;
    allRooms: string;
    gallery: string;
    contact: string;
    booking: string;
    menu: string;
    call: string;
    language: string;
  };
  footer: {
    tagline: string;
    explore: string;
    services: string;
    reception: string;
    wifi: string;
    checkIn: string;
    checkOut: string;
    plan: string;
    planText: string;
    bookingLink: string;
  };
  booking: {
    eyebrow: string;
    title: string;
    checkIn: string;
    checkOut: string;
    adults: string;
    children: string;
    childAges: string;
    childAge: string;
    submit: string;
  };
  home: {
    hero: { eyebrow: string; title: string; italic: string; description: string; cta: string; imageAlt: string };
    services: { eyebrow: string; title: string; italic: string; items: readonly ServiceItem[] };
    gallery: { eyebrow: string; title: string; italic: string; description: string; cta: string; imageAlt: string };
    rooms: {
      eyebrow: string; title: string; italic: string; all: string; featuredLabel: string;
      featuredTitle: string; featuredText: string; cta: string; count: string; wifi: string;
      safe: string; inspect: string; imageAlt: string;
    };
    perks: readonly ServiceItem[];
    about: { eyebrow: string; title: string; italic: string; text: string; cta: string; imageAlt: string };
    spaces: { eyebrow: string; title: string; italic: string; items: readonly SpaceItem[] };
  };
  catalog: {
    heroTitle: string; heroText: string; heroAlt: string; all: string; roomLabel: string;
    details: string; wifi: string; perks: readonly ServiceItem[];
  };
  detail: {
    home: string; rooms: string; viewAll: string; wifi: string; minibarWater: string;
    about: string; experience: string; bodySuffix: string; bookingEyebrow: string;
    bookingTitle: string; bookingText: string; times: string; other: string;
    recommendations: string; allRooms: string; verifiedAmenities: readonly string[];
    extraItems: readonly string[];
  };
  gallery: {
    heroEyebrow: string; heroTitle: string; heroItalic: string; heroText: string; heroAlt: string;
    introEyebrow: string; introTitle: string; introItalic: string; introText: string;
    all: string; hotel: string; result: string; roomCaption: string; roomAlt: string;
    hotelDescriptions: readonly string[];
  };
  about: {
    heroEyebrow: string; heroTitle: string; heroItalic: string; heroText: string;
    approachEyebrow: string; approachTitle: string; approachItalic: string;
    paragraphs: readonly [string, string]; valuesEyebrow: string; valuesTitle: string;
    valuesItalic: string; values: readonly ValueItem[]; imageAlts: readonly [string, string, string];
  };
  contact: {
    heroEyebrow: string; heroTitle: string; heroItalic: string; heroText: string; heroAlt: string;
    mapTitle: string; checkInTitle: string; checkInText: string; checkOutTitle: string;
    checkOutText: string; receptionTitle: string; receptionText: string;
    addressEyebrow: string; addressTitle: string; directions: string;
  };
  a11y: {
    brandHome: string; mainMenu: string; roomOptions: string; callNumber: string;
    openMenu: string; mobileMenu: string; footerMenu: string; poweredBy: string;
    bookingSearch: string; roomTypes: string; hotelRoomOptions: string; roomDetails: string;
    roomOverview: string; roomShortFacts: string; stayBenefits: string; breadcrumb: string;
    roomQuickFacts: string; roomAmenities: string; roomBookingSearch: string; roomInterior: string;
    hotelServices: string; galleryCategories: string; openFullscreen: string;
    galleryDialog: string; closeGallery: string; previousPhoto: string; nextPhoto: string;
    thumbnails: string; showPhoto: string; roomPhotos: string; roomPhoto: string;
    openRoomGallery: string; photoCount: string; previousRoomPhoto: string; nextRoomPhoto: string;
    chatOpen: string; liveSupport: string;
  };
};

export const messages: Record<"tr" | "en" | "de" | "ru", Messages> = {
  tr: {
    meta: {
      description: "Antalya'nın merkezinde sade, işlevsel ve konforlu bir konaklama. Mİ Hotel Boutique oda seçeneklerini inceleyin ve doğrudan rezervasyon yapın.",
      roomsTitle: "Odalar", roomsDescription: "Farklı konaklama ihtiyaçlarına uygun Eco, Double, Triple ve Aile Odası seçeneklerini inceleyin.",
      galleryTitle: "Galeri", galleryDescription: "Mİ Hotel Boutique ortak alanlarını, Eco, Double, Triple ve Aile odalarını fotoğraflarla keşfedin.",
      aboutTitle: "Hakkımızda", aboutDescription: "Mİ Hotel Boutique'in sade konaklama yaklaşımını ve misafir deneyimini keşfedin.",
      contactTitle: "Konum ve İletişim", contactDescription: "Mİ Hotel Boutique adresi ve iletişim bilgileri.", roomNotFound: "Oda Bulunamadı",
    },
    nav: { home: "Ana Sayfa", rooms: "Odalar", allRooms: "Tüm Odalar", gallery: "Galeri", contact: "Konum & İletişim", booking: "Rezervasyon", menu: "Menü", call: "Ara:", language: "Dil" },
    footer: { tagline: "Antalya'nın merkezinde sade, işlevsel ve özenli bir konaklama.", explore: "Keşfet", services: "Misafir Hizmetleri", reception: "7/24 resepsiyon", wifi: "Ücretsiz Wi-Fi", checkIn: "Giriş 14:00", checkOut: "Çıkış 12:00", plan: "Konaklamanızı planlayın", planText: "Güncel oda seçeneklerini, müsaitliği ve fiyatları rezervasyon sayfamızda görüntüleyin.", bookingLink: "Rezervasyona git" },
    booking: { eyebrow: "Doğrudan rezervasyon", title: "Konaklama tarihlerinizi seçin", checkIn: "Giriş", checkOut: "Çıkış", adults: "Yetişkin", children: "Çocuk", childAges: "Çocuk yaşları", childAge: "{index}. çocuk yaşı", submit: "Müsaitliği Kontrol Et" },
    home: {
      hero: { eyebrow: "Antalya'nın kalbinde", title: "Konforu hissedin,", italic: "hikâyenizi yaşayın.", description: "Antalya'daki şehir konaklamanız için sade tasarım, işlevsel odalar ve özenli hizmet bir arada.", cta: "Mİ Hotel'i keşfedin", imageAlt: "Mİ Hotel Boutique mitolojik kabartmalı lobi ve resepsiyon alanı" },
      services: { eyebrow: "Otel hizmetleri", title: "Konforunuz için", italic: "yanınızda.", items: [
        { title: "7/24 Resepsiyon", text: "Resepsiyon ekibimize günün her saati ulaşabilirsiniz." },
        { title: "Ücretsiz Wi-Fi", text: "Otelin tüm alanlarında ücretsiz internet erişimi." },
        { title: "Ücretsiz Minibar", text: "Odanızdaki minibarda yalnızca ücretsiz su sunulur." },
        { title: "Oda Servisi", text: "Konaklamanız boyunca oda servisi hizmetimizden yararlanabilirsiniz." },
        { title: "Çamaşırhane", text: "Talep üzerine, ek ücret karşılığında sunulur." },
      ] },
      gallery: { eyebrow: "Otel galerisi", title: "Mİ Hotel'i", italic: "yakından keşfedin.", description: "Ortak alanlarımızı ve dört farklı oda tipimizi fotoğraflarla inceleyin.", cta: "Tüm fotoğrafları gör", imageAlt: "Mİ Hotel Boutique lobi ve resepsiyon alanı" },
      rooms: { eyebrow: "Odalarımız", title: "Konforunuz için", italic: "tasarlandı.", all: "Tüm odaları incele", featuredLabel: "Odalarımız", featuredTitle: "Dört Farklı Oda Seçeneği", featuredText: "Eco, Double, Triple ve Aile Odası seçenekleri arasından seyahatinize uygun odayı seçin.", cta: "Odaları incele", count: "4 oda seçeneği", wifi: "Ücretsiz Wi-Fi", safe: "Kasa", inspect: "İncele", imageAlt: "Mİ Hotel Boutique oda seçenekleri" },
      perks: [
        { title: "7/24 Resepsiyon", text: "Günün her saati destek." }, { title: "Ücretsiz Wi-Fi", text: "Otelin tüm alanlarında." },
        { title: "Ücretsiz Minibar", text: "Yalnızca ücretsiz su içerir." }, { title: "Çamaşırhane", text: "Talep üzerine, ek ücretle." },
      ],
      about: { eyebrow: "Hakkımızda", title: "Sadelik ve konforun", italic: "buluşma noktası.", text: "Aydınlık ortak alanlar, işlevsel odalar ve 7/24 ulaşılabilen resepsiyon ekibiyle Antalya konaklamanız boyunca sade ve özenli bir deneyim sunuyoruz.", cta: "Daha fazlasını keşfedin", imageAlt: "Mİ Hotel Boutique resepsiyon alanı" },
      spaces: { eyebrow: "Mİ Hotel'i keşfedin", title: "Mİ Hotel'i", italic: "yakından keşfedin.", items: [
        { title: "Resepsiyon", text: "Günün her saati hizmet" }, { title: "Lobi", text: "Dinlenme ve bekleme alanı" }, { title: "Oturma Alanı", text: "Konforlu dinlenme alanı" }, { title: "Ortak Alanlar", text: "İç mekânlar ve atmosfer" }, { title: "Mİ Hotel", text: "Antalya, Muratpaşa" },
      ] },
    },
    catalog: { heroTitle: "Odalarımız", heroText: "Farklı konaklama ihtiyaçlarına uygun Eco, Double, Triple ve Aile Odası seçeneklerimizi inceleyin.", heroAlt: "Mİ Hotel Boutique Aile Odası", all: "Tüm Odalar", roomLabel: "Oda", details: "Detayları incele", wifi: "Ücretsiz Wi-Fi", perks: [
      { title: "7/24 Resepsiyon", text: "Resepsiyon ekibimize günün her saati ulaşabilirsiniz." }, { title: "Ücretsiz Wi-Fi", text: "Otelin tüm alanlarında ücretsiz internet erişimi." }, { title: "Oda İçi Donanım", text: "Kettle, sıcak içecek seti ve yalnızca ücretsiz su içeren minibar." }, { title: "Misafir Hizmetleri", text: "Oda servisi ve talep üzerine ücretli çamaşırhane hizmeti." },
    ] },
    detail: { home: "Ana Sayfa", rooms: "Odalar", viewAll: "Tüm odaları görüntüle", wifi: "Ücretsiz Wi-Fi", minibarWater: "Ücretsiz minibar · yalnızca su", about: "Oda hakkında", experience: "{room} deneyimi", bodySuffix: "Mİ Hotel Boutique'in sade ve işlevsel tasarım anlayışını yansıtan odanızda konforlu bir şehir konaklaması için ihtiyaç duyacağınız temel olanaklar bulunur.", bookingEyebrow: "Doğrudan rezervasyon", bookingTitle: "Konaklamanızı planlayın", bookingText: "Seçtiğiniz tarihlere ait güncel fiyat ve müsaitlik bilgilerini rezervasyon sayfamızda görüntüleyebilirsiniz.", times: "Standart giriş 14:00 · Standart çıkış 12:00", other: "Diğer seçenekler", recommendations: "Diğer oda seçenekleri", allRooms: "Tüm odalar", verifiedAmenities: ["Ücretsiz Wi-Fi", "Oda kasası", "Kettle ve sıcak içecek seti", "Ücretsiz minibar", "Yalnızca ücretsiz su", "Şampuan ve hijyen ürünleri", "Terlik", "Oda servisi", "Ücretli çamaşırhane", "7/24 resepsiyon"], extraItems: ["Oda servisi", "Ücretli çamaşırhane hizmeti", "7/24 resepsiyon desteği"] },
    gallery: { heroEyebrow: "Galeri", heroTitle: "Otelimizi ve odalarımızı", heroItalic: "yakından keşfedin.", heroText: "Mİ Hotel Boutique'in ortak alanlarından dört farklı oda tipine kadar tüm fotoğraflarını inceleyin.", heroAlt: "Mİ Hotel Boutique lobi ve resepsiyon alanı", introEyebrow: "Fotoğraf galerisi", introTitle: "Mİ Hotel'in", introItalic: "tüm detayları.", introText: "Otelimizin ortak alanlarını ve tüm oda tiplerini fotoğraflarla keşfedin. Bir fotoğraf seçerek tam ekran galeriyi açabilir, görseller arasında geçiş yapabilirsiniz.", all: "Tümü", hotel: "Otel ve Ortak Alanlar", result: "{count} fotoğraf gösteriliyor", roomCaption: "{room} · {index} / {count}", roomAlt: "{room} iç mekân görünümü {index} / {count}", hotelDescriptions: ["Bitkili duvar ve beyaz merdiven", "Otel dış cephesi ve giriş", "Koridordaki duvar resmi", "Lobi oturma alanı", "Dekoratif at ve kanatlı figür kabartması", "Aydınlık otel koridoru", "Resepsiyon yanındaki oturma alanı ve duvar kabartması", "Geniş resepsiyon görünümü", "Lobi ve resepsiyon alanı", "Bitkilerle ayrılmış koridor ve oturma alanı", "Resepsiyon bankosu", "Lobi oturma alanı ve koridorlar", "Beyaz merdiven ve sarkıt aydınlatmalar"] },
    about: { heroEyebrow: "Hakkımızda", heroTitle: "Konforu sadeleştiren", heroItalic: "bir butik otel.", heroText: "İyi bir konaklamanın temiz, düzenli ve ihtiyaçlara cevap veren ayrıntılarla başladığına inanıyoruz.", approachEyebrow: "Yaklaşımımız", approachTitle: "İhtiyacınız olan konfor,", approachItalic: "yalın bir anlayışla.", paragraphs: ["Mİ Hotel Boutique, Antalya'daki şehir seyahatleri için sade, işlevsel ve konforlu bir konaklama deneyimi sunar. Dört farklı oda tipimiz, farklı konaklama ihtiyaçlarına uygun seçenekler sağlar.", "Ücretsiz Wi-Fi, oda servisi, ek ücretli çamaşırhane hizmeti ve 7/24 ulaşılabilen resepsiyon ekibimiz konaklamanız boyunca yanınızdadır."], valuesEyebrow: "Mİ deneyimi", valuesTitle: "Üç temel", valuesItalic: "değer.", values: [{ title: "Sadelik", text: "Gereksiz ayrıntılardan arınmış, rahat ve anlaşılır alanlar." }, { title: "İşlevsellik", text: "Konaklamayı kolaylaştıran, günlük ihtiyaçlara cevap veren çözümler." }, { title: "Misafirperverlik", text: "Günün her saati ulaşılabilir, ilgili ve çözüm odaklı hizmet." }], imageAlts: ["Mİ Hotel Boutique resepsiyon ve lobi alanı", "Mİ Hotel Boutique koridoru", "Mİ Hotel Boutique merdiven alanı"] },
    contact: { heroEyebrow: "Konum & İletişim", heroTitle: "Konaklamanız için", heroItalic: "temel bilgiler.", heroText: "Giriş, çıkış ve resepsiyon hizmetlerine ilişkin temel bilgilere buradan ulaşabilirsiniz.", heroAlt: "Mİ Hotel Boutique dış cephesi", mapTitle: "Google Maps üzerinde Mİ Hotel Boutique — {address}", checkInTitle: "Giriş saati", checkInText: "Erken giriş talepleri otel müsaitliğine bağlı olarak değerlendirilir ve önceden garanti edilemez.", checkOutTitle: "Çıkış saati", checkOutText: "Standart çıkış saatimiz 12:00'dir.", receptionTitle: "Resepsiyon", receptionText: "Oda telefonundan 0'ı tuşlayarak resepsiyon ekibimize 7/24 ulaşabilirsiniz.", addressEyebrow: "Adres & Yol Tarifi", addressTitle: "Mİ Hotel Boutique'e ulaşın.", directions: "Yol Tarifi Al" },
    a11y: { brandHome: "Mİ Hotel Boutique ana sayfa", mainMenu: "Ana menü", roomOptions: "Oda seçenekleri", callNumber: "{phone} numarasını ara", openMenu: "Menüyü aç", mobileMenu: "Mobil menü", footerMenu: "Alt menü", poweredBy: "Powered by DGTLFACE — DGTLFACE web sitesini yeni sekmede aç", bookingSearch: "Rezervasyon arama", roomTypes: "Oda tipleri", hotelRoomOptions: "Mİ Hotel Boutique oda seçenekleri", roomDetails: "{room} detaylarını görüntüle", roomOverview: "{room} genel görünümü", roomShortFacts: "{room} kısa bilgiler", stayBenefits: "Konaklama ayrıcalıkları", breadcrumb: "Sayfa yolu", roomQuickFacts: "Oda kısa bilgileri", roomAmenities: "Oda olanakları", roomBookingSearch: "Bu oda için rezervasyon arama", roomInterior: "{room} iç mekânı", hotelServices: "Otel hizmet bilgileri", galleryCategories: "Galeri kategorileri", openFullscreen: "{alt}; tam ekran galeride aç", galleryDialog: "{category} fotoğraf galerisi", closeGallery: "Galeriyi kapat", previousPhoto: "Önceki fotoğraf", nextPhoto: "Sonraki fotoğraf", thumbnails: "Galeri küçük resimleri", showPhoto: "{index}. fotoğrafı göster", roomPhotos: "{room} fotoğrafları", roomPhoto: "{room} fotoğrafı {index} / {count}; galeride aç", openRoomGallery: "{room} fotoğraf galerisini aç, fotoğraf {index}", photoCount: "{count} fotoğraf", previousRoomPhoto: "Önceki oda fotoğrafı", nextRoomPhoto: "Sonraki oda fotoğrafı", chatOpen: "Mİ Hotel canlı destek sohbetini aç", liveSupport: "Canlı destek" },
  },
  en: {
    meta: { description: "A thoughtfully designed city stay in central Antalya. Explore Mİ Hotel Boutique's four room types and book directly.", roomsTitle: "Rooms", roomsDescription: "Explore Eco, Double, Triple and Family Rooms designed for different stays at Mİ Hotel Boutique.", galleryTitle: "Gallery", galleryDescription: "Explore photos of Mİ Hotel Boutique's shared spaces and all room categories.", aboutTitle: "About Us", aboutDescription: "Discover Mİ Hotel Boutique's thoughtful approach to comfortable city stays.", contactTitle: "Location and Contact", contactDescription: "Mİ Hotel Boutique address, contact information and directions.", roomNotFound: "Room Not Found" },
    nav: { home: "Home", rooms: "Rooms", allRooms: "All Rooms", gallery: "Gallery", contact: "Location & Contact", booking: "Book Now", menu: "Menu", call: "Call:", language: "Language" },
    footer: { tagline: "A thoughtfully designed and comfortable city stay in central Antalya.", explore: "Explore", services: "Guest Services", reception: "24-hour reception", wifi: "Complimentary Wi-Fi", checkIn: "Check-in 14:00", checkOut: "Check-out 12:00", plan: "Plan your stay", planText: "View current room options, availability and rates on our booking page.", bookingLink: "Go to booking" },
    booking: { eyebrow: "Direct booking", title: "Select your stay dates", checkIn: "Check-in", checkOut: "Check-out", adults: "Adults", children: "Children", childAges: "Children's ages", childAge: "Age of child {index}", submit: "Check Availability" },
    home: {
      hero: { eyebrow: "In the heart of Antalya", title: "Feel the comfort,", italic: "live your story.", description: "Thoughtfully arranged rooms and attentive service come together for a comfortable stay in Antalya.", cta: "Discover Mİ Hotel", imageAlt: "Mİ Hotel Boutique lobby and reception area with a mythological relief" },
      services: { eyebrow: "Hotel services", title: "Thoughtful touches", italic: "throughout your stay.", items: [{ title: "24-hour reception", text: "Our reception team is available around the clock." }, { title: "Complimentary Wi-Fi", text: "Complimentary internet access is available throughout the hotel." }, { title: "Complimentary Minibar", text: "The minibar in your room contains complimentary water only." }, { title: "Room Service", text: "Room service is available throughout your stay." }, { title: "Laundry Service", text: "Available on request for an additional fee." }] },
      gallery: { eyebrow: "Hotel gallery", title: "Discover Mİ Hotel", italic: "up close.", description: "Explore our shared spaces and four room types through photographs.", cta: "View all photos", imageAlt: "Mİ Hotel Boutique lobby and reception area" },
      rooms: { eyebrow: "Our rooms", title: "Designed for", italic: "your comfort.", all: "View all rooms", featuredLabel: "Our rooms", featuredTitle: "Four Room Options", featuredText: "Choose from Eco, Double, Triple and Family Rooms to find the right fit for your stay.", cta: "Explore rooms", count: "4 room options", wifi: "Complimentary Wi-Fi", safe: "Safe", inspect: "View room", imageAlt: "Mİ Hotel Boutique room options" },
      perks: [{ title: "24-hour reception", text: "Support around the clock." }, { title: "Complimentary Wi-Fi", text: "Throughout the hotel." }, { title: "Complimentary Minibar", text: "Complimentary water only." }, { title: "Laundry Service", text: "On request, for an additional fee." }],
      about: { eyebrow: "About us", title: "Where simplicity and comfort", italic: "come together.", text: "Bright shared spaces, thoughtfully arranged rooms and a reception team available around the clock create a comfortable stay in Antalya.", cta: "Discover more", imageAlt: "Mİ Hotel Boutique reception area" },
      spaces: { eyebrow: "Discover Mİ Hotel", title: "Explore Mİ Hotel", italic: "up close.", items: [{ title: "Reception", text: "Service around the clock" }, { title: "Lobby", text: "A place to relax and wait" }, { title: "Seating Area", text: "Comfortable space to unwind" }, { title: "Shared Spaces", text: "Interiors and atmosphere" }, { title: "Mİ Hotel", text: "Antalya, Muratpaşa" }] },
    },
    catalog: { heroTitle: "Our Rooms", heroText: "Explore Eco, Double, Triple and Family Rooms arranged for different stay requirements.", heroAlt: "Mİ Hotel Boutique Family Room", all: "All Rooms", roomLabel: "Room", details: "View details", wifi: "Complimentary Wi-Fi", perks: [{ title: "24-hour reception", text: "Our reception team is available around the clock." }, { title: "Complimentary Wi-Fi", text: "Complimentary internet access is available throughout the hotel." }, { title: "In-room amenities", text: "Kettle, hot-drink facilities and a minibar containing complimentary water only." }, { title: "Guest services", text: "Room service is available; laundry service is offered for an additional fee." }] },
    detail: { home: "Home", rooms: "Rooms", viewAll: "View all rooms", wifi: "Complimentary Wi-Fi", minibarWater: "Complimentary minibar · water only", about: "About the room", experience: "The {room} experience", bodySuffix: "Thoughtfully arranged in Mİ Hotel Boutique's understated style, your room brings together the essentials for a comfortable city stay.", bookingEyebrow: "Direct booking", bookingTitle: "Plan your stay", bookingText: "View current rates and availability for your selected dates on our booking page.", times: "Standard check-in 14:00 · Standard check-out 12:00", other: "Other options", recommendations: "Other room options", allRooms: "All rooms", verifiedAmenities: ["Complimentary Wi-Fi", "In-room safe", "Kettle and hot-drink facilities", "Complimentary minibar", "Complimentary water only", "Shampoo and toiletries", "Slippers", "Room service", "Laundry service for a fee", "24-hour reception"], extraItems: ["Room service", "Laundry service for an additional fee", "24-hour reception support"] },
    gallery: { heroEyebrow: "Gallery", heroTitle: "Explore our hotel and rooms", heroItalic: "up close.", heroText: "Browse every photo, from Mİ Hotel Boutique's shared spaces to its four room types.", heroAlt: "Mİ Hotel Boutique lobby and reception area", introEyebrow: "Photo gallery", introTitle: "Mİ Hotel", introItalic: "in every detail.", introText: "Explore our shared spaces and every room type through photographs. Select a photo to open the full-screen gallery and move between images.", all: "All", hotel: "Hotel & Shared Spaces", result: "Showing {count} photos", roomCaption: "{room} · {index} / {count}", roomAlt: "Interior view of {room}, {index} / {count}", hotelDescriptions: ["Green wall and white staircase", "Hotel exterior and entrance", "Corridor mural", "Lobby seating area", "Decorative relief of a horse and winged figure", "Bright hotel corridor", "Seating area beside reception and wall relief", "Wide view of reception", "Lobby and reception area", "Corridor and seating area divided by plants", "Reception desk", "Lobby seating area and corridors", "White staircase and pendant lights"] },
    about: { heroEyebrow: "About Us", heroTitle: "A boutique hotel", heroItalic: "where comfort feels effortless.", heroText: "We believe a comfortable stay begins with cleanliness, order and thoughtful attention to everyday needs.", approachEyebrow: "Our approach", approachTitle: "The comfort you need,", approachItalic: "thoughtfully considered.", paragraphs: ["Mİ Hotel Boutique offers a simple, functional and comfortable base for city stays in Antalya. Four room types provide options for different travel needs.", "Complimentary Wi-Fi, room service, laundry service for an additional fee and a reception team available around the clock support you throughout your stay."], valuesEyebrow: "The Mİ experience", valuesTitle: "Three core", valuesItalic: "values.", values: [{ title: "Simplicity", text: "Comfortable, intuitive spaces free from unnecessary detail." }, { title: "Functionality", text: "Solutions that simplify your stay and meet everyday needs." }, { title: "Hospitality", text: "Attentive, solution-focused service available at any time of day." }], imageAlts: ["Mİ Hotel Boutique reception and lobby area", "Mİ Hotel Boutique corridor", "Mİ Hotel Boutique staircase area"] },
    contact: { heroEyebrow: "Location & Contact", heroTitle: "Essential information", heroItalic: "for your stay.", heroText: "Everything you need to know about check-in, check-out and reception services.", heroAlt: "Mİ Hotel Boutique exterior", mapTitle: "Mİ Hotel Boutique on Google Maps — {address}", checkInTitle: "Check-in time", checkInText: "Early check-in may be available subject to hotel availability and cannot be guaranteed in advance.", checkOutTitle: "Check-out time", checkOutText: "Our standard check-out time is 12:00.", receptionTitle: "Reception", receptionText: "From your room, dial 0 on the telephone to reach reception.", addressEyebrow: "Address & Directions", addressTitle: "Find Mİ Hotel Boutique.", directions: "Get Directions" },
    a11y: { brandHome: "Mİ Hotel Boutique home page", mainMenu: "Main menu", roomOptions: "Room options", callNumber: "Call {phone}", openMenu: "Open menu", mobileMenu: "Mobile menu", footerMenu: "Footer menu", poweredBy: "Powered by DGTLFACE — open the DGTLFACE website in a new tab", bookingSearch: "Booking search", roomTypes: "Room types", hotelRoomOptions: "Mİ Hotel Boutique room options", roomDetails: "View details for {room}", roomOverview: "Overview of {room}", roomShortFacts: "Key details for {room}", stayBenefits: "Stay benefits", breadcrumb: "Breadcrumb", roomQuickFacts: "Key room details", roomAmenities: "Room amenities", roomBookingSearch: "Booking search for this room", roomInterior: "{room} interior", hotelServices: "Hotel service information", galleryCategories: "Gallery categories", openFullscreen: "{alt}; open in full-screen gallery", galleryDialog: "{category} photo gallery", closeGallery: "Close gallery", previousPhoto: "Previous photo", nextPhoto: "Next photo", thumbnails: "Gallery thumbnails", showPhoto: "Show photo {index}", roomPhotos: "Photos of {room}", roomPhoto: "{room} photo {index} of {count}; open gallery", openRoomGallery: "Open the {room} photo gallery at photo {index}", photoCount: "{count} photos", previousRoomPhoto: "Previous room photo", nextRoomPhoto: "Next room photo", chatOpen: "Open Mİ Hotel live support chat", liveSupport: "Live support" },
  },
  de: {
    meta: { description: "Ein durchdacht gestaltetes Boutiquehotel für einen komfortablen Aufenthalt im Zentrum von Antalya. Zimmer entdecken und direkt buchen.", roomsTitle: "Zimmer", roomsDescription: "Entdecken Sie die Eco-, Doppel-, Dreibett- und Familienzimmer des Mİ Hotel Boutique für unterschiedliche Reisebedürfnisse.", galleryTitle: "Galerie", galleryDescription: "Entdecken Sie die Hotelbereiche und alle Zimmerkategorien des Mİ Hotel Boutique auf Fotos.", aboutTitle: "Über uns", aboutDescription: "Erfahren Sie mehr über das durchdachte Hotelkonzept des Mİ Hotel Boutique und seinen Fokus auf komfortable Stadtaufenthalte.", contactTitle: "Lage und Kontakt", contactDescription: "Adresse, Kontaktinformationen und Anfahrt zum Mİ Hotel Boutique.", roomNotFound: "Zimmer nicht gefunden" },
    nav: { home: "Startseite", rooms: "Zimmer", allRooms: "Alle Zimmer", gallery: "Galerie", contact: "Lage & Kontakt", booking: "Buchen", menu: "Menü", call: "Anrufen:", language: "Sprache" },
    footer: { tagline: "Ein durchdacht gestalteter und komfortabler Stadtaufenthalt im Zentrum von Antalya.", explore: "Entdecken", services: "Gästeservice", reception: "24-Stunden-Rezeption", wifi: "Kostenloses WLAN", checkIn: "Check-in 14:00 Uhr", checkOut: "Check-out 12:00 Uhr", plan: "Planen Sie Ihren Aufenthalt", planText: "Aktuelle Zimmeroptionen, Verfügbarkeiten und Preise finden Sie auf unserer Buchungsseite.", bookingLink: "Zur Buchung" },
    booking: { eyebrow: "Direktbuchung", title: "Reisedaten auswählen", checkIn: "Check-in", checkOut: "Check-out", adults: "Erwachsene", children: "Kinder", childAges: "Alter der Kinder", childAge: "Alter des {index}. Kindes", submit: "Verfügbarkeit prüfen" },
    home: {
      hero: { eyebrow: "Im Herzen von Antalya", title: "Spüren Sie den Komfort,", italic: "leben Sie Ihre Geschichte.", description: "Durchdacht eingerichtete Zimmer und aufmerksamer Service schaffen den passenden Rahmen für Ihren Aufenthalt in Antalya.", cta: "Mİ Hotel entdecken", imageAlt: "Lobby- und Rezeptionsbereich des Mİ Hotel Boutique mit mythologischem Relief" },
      services: { eyebrow: "Hotelleistungen", title: "Durchdachte Details", italic: "für Ihren Aufenthalt.", items: [{ title: "24-Stunden-Rezeption", text: "Unser Rezeptionsteam ist rund um die Uhr erreichbar." }, { title: "Kostenloses WLAN", text: "Kostenloser Internetzugang steht in allen Hotelbereichen zur Verfügung." }, { title: "Kostenfreie Minibar", text: "Die Minibar in Ihrem Zimmer enthält ausschließlich kostenfreies Wasser." }, { title: "Zimmerservice", text: "Auf Wunsch steht Ihnen während Ihres Aufenthalts unser Zimmerservice zur Verfügung." }, { title: "Wäscheservice", text: "Auf Anfrage gegen Gebühr verfügbar." }] },
      gallery: { eyebrow: "Hotelgalerie", title: "Entdecken Sie Mİ Hotel", italic: "aus nächster Nähe.", description: "Entdecken Sie unsere Gemeinschaftsbereiche und vier Zimmertypen auf Fotos.", cta: "Alle Fotos ansehen", imageAlt: "Lobby- und Rezeptionsbereich des Mİ Hotel Boutique" },
      rooms: { eyebrow: "Unsere Zimmer", title: "Für Ihren Komfort", italic: "gestaltet.", all: "Alle Zimmer ansehen", featuredLabel: "Unsere Zimmer", featuredTitle: "Vier Zimmeroptionen", featuredText: "Wählen Sie zwischen Eco-, Doppel-, Dreibett- und Familienzimmern die passende Option für Ihren Aufenthalt.", cta: "Zimmer entdecken", count: "4 Zimmeroptionen", wifi: "Kostenloses WLAN", safe: "Zimmersafe", inspect: "Ansehen", imageAlt: "Zimmerauswahl im Mİ Hotel Boutique" },
      perks: [{ title: "24-Stunden-Rezeption", text: "Rund um die Uhr erreichbar." }, { title: "Kostenloses WLAN", text: "In allen Hotelbereichen." }, { title: "Kostenfreie Minibar", text: "Ausschließlich kostenfreies Wasser." }, { title: "Wäscheservice", text: "Auf Anfrage gegen Gebühr." }],
      about: { eyebrow: "Über uns", title: "Wo Schlichtheit und Komfort", italic: "zusammenfinden.", text: "Helle Hotelbereiche, durchdacht eingerichtete Zimmer und ein rund um die Uhr erreichbares Rezeptionsteam schaffen einen angenehmen Aufenthalt in Antalya.", cta: "Mehr entdecken", imageAlt: "Rezeptionsbereich des Mİ Hotel Boutique" },
      spaces: { eyebrow: "Mİ Hotel entdecken", title: "Mİ Hotel", italic: "aus nächster Nähe.", items: [{ title: "Rezeption", text: "Service rund um die Uhr" }, { title: "Lobby", text: "Bereich zum Entspannen und Warten" }, { title: "Sitzbereich", text: "Komfortabler Rückzugsort" }, { title: "Hotelbereiche", text: "Interieur und Atmosphäre" }, { title: "Mİ Hotel", text: "Antalya, Muratpaşa" }] },
    },
    catalog: { heroTitle: "Unsere Zimmer", heroText: "Entdecken Sie Eco-, Doppel-, Dreibett- und Familienzimmer für unterschiedliche Reisebedürfnisse.", heroAlt: "Familienzimmer im Mİ Hotel Boutique", all: "Alle Zimmer", roomLabel: "Zimmer", details: "Details ansehen", wifi: "Kostenloses WLAN", perks: [{ title: "24-Stunden-Rezeption", text: "Unser Rezeptionsteam ist rund um die Uhr erreichbar." }, { title: "Kostenloses WLAN", text: "Kostenloser Internetzugang steht in allen Hotelbereichen zur Verfügung." }, { title: "Ausstattung im Zimmer", text: "Wasserkocher, Heißgetränke-Set und eine Minibar ausschließlich mit kostenfreiem Wasser." }, { title: "Gästeservice", text: "Zimmerservice ist verfügbar; der Wäscheservice wird gegen Gebühr angeboten." }] },
    detail: { home: "Startseite", rooms: "Zimmer", viewAll: "Alle Zimmer ansehen", wifi: "Kostenloses WLAN", minibarWater: "Kostenfreie Minibar · nur Wasser", about: "Über das Zimmer", experience: "Ihr Aufenthalt im {room}", bodySuffix: "Durchdacht und funktional eingerichtet, bietet Ihr Zimmer alles Wesentliche für einen angenehmen Stadtaufenthalt.", bookingEyebrow: "Direktbuchung", bookingTitle: "Planen Sie Ihren Aufenthalt", bookingText: "Aktuelle Preise und Verfügbarkeiten für Ihre Reisedaten finden Sie auf unserer Buchungsseite.", times: "Standard-Check-in 14:00 Uhr · Standard-Check-out 12:00 Uhr", other: "Weitere Optionen", recommendations: "Weitere Zimmeroptionen", allRooms: "Alle Zimmer", verifiedAmenities: ["Kostenloses WLAN", "Zimmersafe", "Wasserkocher und Heißgetränke-Set", "Kostenfreie Minibar", "Ausschließlich kostenfreies Wasser", "Shampoo und Pflegeprodukte", "Hausschuhe", "Zimmerservice", "Wäscheservice gegen Gebühr", "24-Stunden-Rezeption"], extraItems: ["Zimmerservice", "Wäscheservice gegen Gebühr", "24-Stunden-Rezeption"] },
    gallery: { heroEyebrow: "Galerie", heroTitle: "Entdecken Sie unser Hotel und unsere Zimmer", heroItalic: "aus nächster Nähe.", heroText: "Entdecken Sie alle Fotos – von den Gemeinschaftsbereichen des Mİ Hotel Boutique bis zu seinen vier Zimmertypen.", heroAlt: "Lobby- und Rezeptionsbereich des Mİ Hotel Boutique", introEyebrow: "Fotogalerie", introTitle: "Mİ Hotel", introItalic: "bis ins Detail.", introText: "Entdecken Sie unsere Gemeinschaftsbereiche und alle Zimmertypen auf Fotos. Wählen Sie ein Bild aus, um die Galerie im Vollbildmodus anzusehen.", all: "Alle", hotel: "Hotel & Gemeinschaftsbereiche", result: "{count} Fotos werden angezeigt", roomCaption: "{room} · {index} / {count}", roomAlt: "Innenansicht des {room}, {index} / {count}", hotelDescriptions: ["Begrünte Wand und weiße Treppe", "Hotelfassade und Eingang", "Wandgemälde im Flur", "Sitzbereich in der Lobby", "Dekoratives Relief mit Pferd und geflügelter Figur", "Heller Hotelflur", "Sitzbereich neben der Rezeption und Wandrelief", "Weitläufiger Blick auf die Rezeption", "Lobby- und Rezeptionsbereich", "Durch Pflanzen getrennter Flur- und Sitzbereich", "Rezeptionstresen", "Sitzbereich in der Lobby und Flure", "Weiße Treppe und Pendelleuchten"] },
    about: { heroEyebrow: "Über uns", heroTitle: "Ein Boutiquehotel,", heroItalic: "das Komfort unkompliziert macht.", heroText: "Wir glauben, dass ein angenehmer Aufenthalt mit Sauberkeit, Ordnung und durchdachten Details für den Alltag beginnt.", approachEyebrow: "Unser Ansatz", approachTitle: "Der Komfort, den Sie brauchen,", approachItalic: "durchdacht umgesetzt.", paragraphs: ["Das Mİ Hotel Boutique ist eine schlichte, funktionale und komfortable Unterkunft für Städtereisen nach Antalya. Vier Zimmerkategorien bieten passende Optionen für unterschiedliche Reisebedürfnisse.", "Kostenloses WLAN, Zimmerservice, ein Wäscheservice gegen Gebühr und unser rund um die Uhr erreichbares Rezeptionsteam begleiten Sie während Ihres Aufenthalts."], valuesEyebrow: "Das Mİ Erlebnis", valuesTitle: "Drei zentrale", valuesItalic: "Werte.", values: [{ title: "Schlichtheit", text: "Komfortable, verständlich gestaltete Räume ohne Überflüssiges." }, { title: "Funktionalität", text: "Lösungen, die den Aufenthalt erleichtern und den täglichen Bedürfnissen gerecht werden." }, { title: "Gastfreundschaft", text: "Aufmerksamer, lösungsorientierter Service, der jederzeit erreichbar ist." }], imageAlts: ["Rezeptions- und Lobbybereich des Mİ Hotel Boutique", "Flur des Mİ Hotel Boutique", "Treppenbereich des Mİ Hotel Boutique"] },
    contact: { heroEyebrow: "Lage & Kontakt", heroTitle: "Wichtige Informationen", heroItalic: "für Ihren Aufenthalt.", heroText: "Hier finden Sie alles Wissenswerte zu Check-in, Check-out und Rezeptionsservice.", heroAlt: "Außenansicht des Mİ Hotel Boutique", mapTitle: "Mİ Hotel Boutique auf Google Maps — {address}", checkInTitle: "Check-in-Zeit", checkInText: "Ein früher Check-in ist je nach Verfügbarkeit möglich und kann nicht im Voraus garantiert werden.", checkOutTitle: "Check-out-Zeit", checkOutText: "Unsere reguläre Check-out-Zeit ist 12:00 Uhr.", receptionTitle: "Rezeption", receptionText: "Vom Zimmertelefon erreichen Sie die Rezeption durch Drücken der 0.", addressEyebrow: "Adresse & Anfahrt", addressTitle: "So erreichen Sie das Mİ Hotel Boutique.", directions: "Route anzeigen" },
    a11y: { brandHome: "Startseite des Mİ Hotel Boutique", mainMenu: "Hauptmenü", roomOptions: "Zimmeroptionen", callNumber: "{phone} anrufen", openMenu: "Menü öffnen", mobileMenu: "Mobiles Menü", footerMenu: "Fußzeilenmenü", poweredBy: "Powered by DGTLFACE — DGTLFACE-Website in einem neuen Tab öffnen", bookingSearch: "Buchungssuche", roomTypes: "Zimmertypen", hotelRoomOptions: "Zimmeroptionen im Mİ Hotel Boutique", roomDetails: "Details zum {room} ansehen", roomOverview: "Übersicht des {room}", roomShortFacts: "Kurzinfo zum {room}", stayBenefits: "Vorteile Ihres Aufenthalts", breadcrumb: "Brotkrümelnavigation", roomQuickFacts: "Zimmer-Kurzinfo", roomAmenities: "Zimmerausstattung", roomBookingSearch: "Buchungssuche für dieses Zimmer", roomInterior: "Innenansicht des {room}", hotelServices: "Informationen zu den Hotelleistungen", galleryCategories: "Galeriekategorien", openFullscreen: "{alt}; in der Vollbildgalerie öffnen", galleryDialog: "Fotogalerie: {category}", closeGallery: "Galerie schließen", previousPhoto: "Vorheriges Foto", nextPhoto: "Nächstes Foto", thumbnails: "Galerie-Miniaturbilder", showPhoto: "Foto {index} anzeigen", roomPhotos: "Fotos des {room}", roomPhoto: "Foto {index} von {count} des {room}; Galerie öffnen", openRoomGallery: "Fotogalerie des {room} bei Foto {index} öffnen", photoCount: "{count} Fotos", previousRoomPhoto: "Vorheriges Zimmerfoto", nextRoomPhoto: "Nächstes Zimmerfoto", chatOpen: "Live-Chat des Mİ Hotel öffnen", liveSupport: "Live-Support" },
  },
  ru: {
    meta: { description: "Современное и комфортное проживание в центре Антальи. Познакомьтесь с номерами Mİ Hotel Boutique и забронируйте напрямую.", roomsTitle: "Номера", roomsDescription: "Выберите один из четырёх вариантов размещения Mİ Hotel Boutique: Eco, двухместный, трёхместный или семейный номер.", galleryTitle: "Галерея", galleryDescription: "Посмотрите фотографии общих зон и всех категорий номеров Mİ Hotel Boutique.", aboutTitle: "Об отеле", aboutDescription: "Узнайте больше о продуманном подходе Mİ Hotel Boutique к комфортному городскому отдыху.", contactTitle: "Расположение и контакты", contactDescription: "Адрес Mİ Hotel Boutique, контактная информация и маршрут.", roomNotFound: "Номер не найден" },
    nav: { home: "Главная", rooms: "Номера", allRooms: "Все номера", gallery: "Галерея", contact: "Расположение и контакты", booking: "Забронировать", menu: "Меню", call: "Позвонить:", language: "Язык" },
    footer: { tagline: "Продуманный городской отдых, где простота сочетается с комфортом.", explore: "Разделы", services: "Услуги для гостей", reception: "Круглосуточная стойка регистрации", wifi: "Бесплатный Wi‑Fi", checkIn: "Заезд с 14:00", checkOut: "Выезд до 12:00", plan: "Спланируйте проживание", planText: "Посмотрите актуальные категории номеров, свободные даты и цены на странице бронирования.", bookingLink: "Перейти к бронированию" },
    booking: { eyebrow: "Прямое бронирование", title: "Выберите даты проживания", checkIn: "Заезд", checkOut: "Выезд", adults: "Взрослые", children: "Дети", childAges: "Возраст детей", childAge: "Возраст ребёнка {index}", submit: "Проверить наличие" },
    home: {
      hero: { eyebrow: "В самом сердце Антальи", title: "Почувствуйте комфорт,", italic: "проживите свою историю.", description: "Продуманное пространство и внимательный сервис создают комфортные условия для отдыха в Анталье.", cta: "Откройте для себя Mİ Hotel", imageAlt: "Лобби и стойка регистрации Mİ Hotel Boutique с мифологическим рельефом" },
      services: { eyebrow: "Услуги отеля", title: "Продуманные детали", italic: "для вашего отдыха.", items: [{ title: "Круглосуточная стойка регистрации", text: "Связаться с командой стойки регистрации можно в любое время суток." }, { title: "Бесплатный Wi‑Fi", text: "Бесплатный доступ в интернет предоставляется на всей территории отеля." }, { title: "Бесплатный мини-бар", text: "В мини-баре предоставляется только бесплатная вода." }, { title: "Обслуживание номеров", text: "Услуга доступна на протяжении всего вашего проживания." }, { title: "Услуги прачечной", text: "Предоставляются по запросу за дополнительную плату." }] },
      gallery: { eyebrow: "Галерея отеля", title: "Познакомьтесь с Mİ Hotel", italic: "поближе.", description: "Рассмотрите на фотографиях общественные зоны и четыре типа номеров.", cta: "Посмотреть все фотографии", imageAlt: "Лобби и стойка регистрации Mİ Hotel Boutique" },
      rooms: { eyebrow: "Наши номера", title: "Созданы для", italic: "вашего комфорта.", all: "Все номера", featuredLabel: "Наши номера", featuredTitle: "Четыре варианта размещения", featuredText: "Выберите подходящий вариант: Eco, двухместный, трёхместный или семейный номер.", cta: "Посмотреть номера", count: "4 варианта", wifi: "Бесплатный Wi‑Fi", safe: "Сейф", inspect: "Подробнее", imageAlt: "Варианты номеров Mİ Hotel Boutique" },
      perks: [{ title: "Круглосуточная стойка регистрации", text: "Помощь в любое время суток." }, { title: "Бесплатный Wi‑Fi", text: "На всей территории отеля." }, { title: "Бесплатный мини-бар", text: "Только бесплатная вода." }, { title: "Услуги прачечной", text: "По запросу за дополнительную плату." }],
      about: { eyebrow: "Об отеле", title: "Место, где простота и комфорт", italic: "соединяются.", text: "Светлые общие зоны, функциональные номера и круглосуточная стойка регистрации создают комфортные условия для отдыха в Анталье.", cta: "Узнать больше", imageAlt: "Стойка регистрации Mİ Hotel Boutique" },
      spaces: { eyebrow: "Откройте для себя Mİ Hotel", title: "Mİ Hotel", italic: "в каждой детали.", items: [{ title: "Стойка регистрации", text: "Круглосуточное обслуживание" }, { title: "Лобби", text: "Место для отдыха и ожидания" }, { title: "Зона отдыха", text: "Комфортное пространство для отдыха" }, { title: "Общие зоны", text: "Интерьеры и атмосфера" }, { title: "Mİ Hotel", text: "Анталья, Муратпаша" }] },
    },
    catalog: { heroTitle: "Наши номера", heroText: "Выберите подходящий вариант размещения: Eco, двухместный, трёхместный или семейный номер.", heroAlt: "Семейный номер Mİ Hotel Boutique", all: "Все номера", roomLabel: "Номер", details: "Подробнее", wifi: "Бесплатный Wi‑Fi", perks: [{ title: "Круглосуточная стойка регистрации", text: "Связаться с командой стойки регистрации можно в любое время суток." }, { title: "Бесплатный Wi‑Fi", text: "Бесплатный доступ в интернет предоставляется на всей территории отеля." }, { title: "Оснащение номера", text: "Чайник, набор для горячих напитков и бесплатный мини-бар только с водой." }, { title: "Услуги для гостей", text: "Доступно обслуживание номеров; услуги прачечной предоставляются за дополнительную плату." }] },
    detail: { home: "Главная", rooms: "Номера", viewAll: "Посмотреть все номера", wifi: "Бесплатный Wi‑Fi", minibarWater: "Бесплатный мини-бар · только вода", about: "О номере", experience: "Отдых в номере «{room}»", bodySuffix: "Лаконичный и функциональный интерьер объединяет всё необходимое для комфортного проживания в Анталье.", bookingEyebrow: "Прямое бронирование", bookingTitle: "Спланируйте проживание", bookingText: "Актуальные цены и свободные даты доступны на странице онлайн-бронирования.", times: "Стандартное время заезда — 14:00 · выезда — 12:00", other: "Другие варианты", recommendations: "Другие категории номеров", allRooms: "Все номера", verifiedAmenities: ["Бесплатный Wi‑Fi", "Сейф в номере", "Чайник и набор для горячих напитков", "Бесплатный мини-бар", "Только бесплатная вода", "Шампунь и средства гигиены", "Тапочки", "Обслуживание номеров", "Прачечная за дополнительную плату", "Круглосуточная стойка регистрации"], extraItems: ["Обслуживание номеров", "Прачечная за дополнительную плату", "Круглосуточная стойка регистрации"] },
    gallery: { heroEyebrow: "Галерея", heroTitle: "Познакомьтесь с нашим отелем и номерами", heroItalic: "поближе.", heroText: "Посмотрите все фотографии Mİ Hotel Boutique — от общих зон до четырёх типов номеров.", heroAlt: "Лобби и стойка регистрации Mİ Hotel Boutique", introEyebrow: "Фотогалерея", introTitle: "Mİ Hotel", introItalic: "в каждой детали.", introText: "Рассмотрите на фотографиях общие зоны и все типы номеров. Выберите изображение, чтобы открыть полноэкранную галерею.", all: "Все", hotel: "Отель и общие зоны", result: "Фотографий: {count}", roomCaption: "{room} · {index} / {count}", roomAlt: "Интерьер номера «{room}», {index} / {count}", hotelDescriptions: ["Стена с растениями и белая лестница", "Фасад отеля и вход", "Настенная роспись в коридоре", "Зона отдыха в лобби", "Декоративный рельеф с лошадью и крылатой фигурой", "Светлый коридор отеля", "Зона отдыха у стойки регистрации и настенный рельеф", "Панорамный вид на стойку регистрации", "Лобби и зона регистрации", "Коридор и зона отдыха, разделённые растениями", "Стойка регистрации", "Зона отдыха в лобби и коридоры", "Белая лестница и подвесные светильники"] },
    about: { heroEyebrow: "Об отеле", heroTitle: "Бутик-отель,", heroItalic: "где комфорт — это просто.", heroText: "Мы верим, что комфортное проживание начинается с чистоты, порядка и внимания к деталям.", approachEyebrow: "Наш подход", approachTitle: "Всё необходимое —", approachItalic: "без лишнего.", paragraphs: ["Mİ Hotel Boutique предлагает лаконичное, функциональное и комфортное размещение для поездок в Анталью. Четыре категории номеров отвечают разным потребностям гостей.", "Бесплатный Wi‑Fi, обслуживание номеров, платные услуги прачечной и круглосуточная стойка регистрации доступны на протяжении всего проживания."], valuesEyebrow: "Атмосфера Mİ", valuesTitle: "Три главные", valuesItalic: "ценности.", values: [{ title: "Простота", text: "Удобные и понятные пространства без лишних деталей." }, { title: "Функциональность", text: "Решения, которые упрощают проживание и отвечают повседневным потребностям." }, { title: "Гостеприимство", text: "Внимательный сервис, готовый помочь и найти решение в любое время суток." }], imageAlts: ["Стойка регистрации и лобби Mİ Hotel Boutique", "Коридор Mİ Hotel Boutique", "Лестничная зона Mİ Hotel Boutique"] },
    contact: { heroEyebrow: "Расположение и контакты", heroTitle: "Основная информация", heroItalic: "для вашего проживания.", heroText: "Здесь собрана основная информация о заезде, выезде и работе стойки регистрации.", heroAlt: "Фасад Mİ Hotel Boutique", mapTitle: "Mİ Hotel Boutique на Google Картах — {address}", checkInTitle: "Время заезда", checkInText: "Запросы на ранний заезд рассматриваются при наличии свободных номеров и не могут быть гарантированы заранее.", checkOutTitle: "Время выезда", checkOutText: "Стандартное время выезда — 12:00.", receptionTitle: "Стойка регистрации", receptionText: "Наберите 0 на телефоне в номере, чтобы связаться со стойкой регистрации в любое время суток.", addressEyebrow: "Адрес и маршрут", addressTitle: "Как добраться до Mİ Hotel Boutique.", directions: "Построить маршрут" },
    a11y: { brandHome: "Главная страница Mİ Hotel Boutique", mainMenu: "Главное меню", roomOptions: "Варианты номеров", callNumber: "Позвонить по номеру {phone}", openMenu: "Открыть меню", mobileMenu: "Мобильное меню", footerMenu: "Меню в нижней части страницы", poweredBy: "Powered by DGTLFACE — открыть сайт DGTLFACE в новой вкладке", bookingSearch: "Поиск бронирования", roomTypes: "Типы номеров", hotelRoomOptions: "Варианты номеров Mİ Hotel Boutique", roomDetails: "Посмотреть подробности о номере «{room}»", roomOverview: "Общий вид номера «{room}»", roomShortFacts: "Краткая информация о номере «{room}»", stayBenefits: "Преимущества проживания", breadcrumb: "Навигационная цепочка", roomQuickFacts: "Краткая информация о номере", roomAmenities: "Удобства в номере", roomBookingSearch: "Поиск бронирования этого номера", roomInterior: "Интерьер номера «{room}»", hotelServices: "Информация об услугах отеля", galleryCategories: "Категории галереи", openFullscreen: "{alt}; открыть в полноэкранной галерее", galleryDialog: "Фотогалерея: {category}", closeGallery: "Закрыть галерею", previousPhoto: "Предыдущее фото", nextPhoto: "Следующее фото", thumbnails: "Миниатюры галереи", showPhoto: "Показать фото {index}", roomPhotos: "Фотографии номера «{room}»", roomPhoto: "Фото номера «{room}», {index} из {count}; открыть галерею", openRoomGallery: "Открыть галерею номера «{room}» с фото {index}", photoCount: "Фото: {count}", previousRoomPhoto: "Предыдущее фото номера", nextRoomPhoto: "Следующее фото номера", chatOpen: "Открыть чат поддержки Mİ Hotel", liveSupport: "Онлайн-поддержка" },
  },
};
